# Generated by Django 5.1.5 on 2025-07-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0002_about_achievements_contact_contactme_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
