# Generated by Django 5.1.5 on 2025-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0003_rename_title_education_college_remove_about_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='color_class',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=75, help_text='Enter percentage (0-100)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer')], max_length=100, unique=True),
        ),
    ]
