# Generated by Django 5.1.5 on 2025-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0004_remove_skill_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
