# Generated by Django 5.1.5 on 2025-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0005_contact_mail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('rights_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
