# Generated by Django 5.1.5 on 2025-08-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0007_logo_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='image',
            new_name='src',
        ),
    ]
