# Generated by Django 5.1.5 on 2025-08-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0008_rename_image_logo_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Port/about'),
        ),
    ]
