# Generated by Django 5.1.5 on 2025-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Port', '0009_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(default='resumes/default_resume.pdf', upload_to='resumes/'),
        ),
    ]
