services:
  - type: web
    name: portfolio-site # or whatever your project name is
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn spamroko.wsgi:application
